apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhpam-trial
  namespace: rhpam-monitoring
spec:
  environment: rhpam-trial
  objects:
    servers:
      - kafkaJbpmEventEmitters:
          bootstrapServers: 'my-cluster-kafka-brokers:9092'
          processesTopicName: rhpam-processes
          tasksTopicName: rhpam-tasks

