apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: amq-channel
  namespace: rhpam-monitoring
spec:
  pathname: 'https://github.com/tosin2013/event-emitter-kafka.git'
  type: GitHub