apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: pam-channel
  namespace: rhpam-monitoring
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: ''
spec:
  pathname: 'https://github.com/tosin2013/event-emitter-kafka.git'
  type: GitHub