apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: amq-deployment
  namespace: openshift-operators
spec:
  selector:
    matchExpressions:
      - key: deployment  
        operator: In
        values:
        - amq-deployment
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription