apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: local-cluster
  namespace: openshift-operators
spec:
  clusterSelector:
    matchLabels:
      name: local-cluster
