apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    tectonic-visibility: ocs
    certified: 'true'
    olm.targetNamespaces: rhpam-monitoring
  name: businessautomation-operator
  namespace: rhpam-monitoring
  labels:
    olm.api.4b35733eb82922c6: provided
    operator-businessautomation: 'true'
    operatorframework.io/arch.amd64: supported
    operatorframework.io/os.linux: supported
    operators.coreos.com/businessautomation-operator.rhpam-monitoring: ''
spec:
  channel: stable
  installPlanApproval: Automatic
  name: businessautomation-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: businessautomation-operator.7.11.1-1