apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: businessautomation-operator
  namespace: rhpam-monitoring
spec:
  channel: stable
  installPlanApproval: Automatic
  name: businessautomation-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: businessautomation-operator.7.11.1-1
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: true
      type: MultiNamespace
    - supported: true
      type: AllNamespaces